#include <nds/ndstypes.h>
#include <nds.h>
#include <gl2d.h>
#include "gfx.h"
#include "set.h"


glImage tex[64];

#define STAR_INDEX 57
#define STAR_FRAME_COUNT 5

struct Anim {
    int32 dest_x;
	int32 dest_y;
    int32 rot;
    int32 scale;

    u8 animating;
    u8 frames;
    u8 sprite;
    u8 frameCtr;
    int animSpeed;
    int timeCtr;

    int32 velx;
    int32 vely;
    int32 velrot;
    int tp;
    int dead;
} ;

struct Anim sprites[64];
int spritesCount = 0;
const int screenBounds = 332;
const int velx = 1;

void initAnim(struct Anim *a, int sprite, int frame_count){
	a->sprite = sprite;
    a->frames = frame_count;
    a->frameCtr = 0;
    a->animating = 1;
    a->animSpeed = 15;
	a->dest_x = 0;
	a->dest_y = 0;
    a->velx = 0;
    a->vely = 0;
    a->velrot  = 0;
    a->scale = 1<<12;
    a->tp = 1;
    spritesCount++;
}

void nextFrame(struct Anim* a){
	
    a->timeCtr++;
    if(a->timeCtr > a->animSpeed && a->animating) {
        a->timeCtr = 0;
        a->frameCtr = ((a->frameCtr+1) % a->frames);
    }
    
    a->rot    += a->velrot;
    a->dest_x += (a->velx*a->scale);
    a->dest_y += (a->vely*a->scale);

    if((a->dest_x>>12) > screenBounds) { 
		a->dest_x = (-50)<<12;  
		a->frameCtr = rand()%a->frames;
	}
    
}

void drawAnim(struct Anim *a){
    if(!a->dead)
    {
        glSpriteRotateScale(
			a->dest_x>>12,
			a->dest_y>>12,
			a->rot,
			a->scale<<1,
			GL_FLIP_NONE,
			&tex[a->sprite + a->frameCtr]);
	}
}

void initFrame(){
    //set mode 5, enable BG0 and set it to 3D
	videoSetMode( MODE_5_3D );
	videoSetModeSub( MODE_0_2D  );

	consoleDemoInit();
	// Initialize GL in 3d mode
	glScreen2D();
	// Set  Bank A to texture (128 kb)
	vramSetBankA( VRAM_A_TEXTURE );

	// Allocate VRAM bank for all the palettes
	vramSetBankE(VRAM_E_TEX_PALETTE);  


	//use this to load sprites which are irregular sizes in one sheet ie 4x4 then 2x4 etc
	// const unsigned int coords[] = {
	// 	0,0,16,16,
	// 	16,0,16,16,
	// 	0,16,16,16,
	// 	16,16,16,16
	// };

    // int tid = 
	// 	glLoadSpriteSet( tex,			// pointer to glImage array
	// 				   4,				
	// 				   coords,
	// 				   GL_RGB256,		// texture type for glTexImage2D() in videoGL.h
	// 				   TEXTURE_SIZE_32,	// sizeX for glTexImage2D() in videoGL.h
	// 				   TEXTURE_SIZE_32,	// sizeY for glTexImage2D() in videoGL.h
	// 				   GL_TEXTURE_WRAP_S|GL_TEXTURE_WRAP_T|TEXGEN_OFF|GL_TEXTURE_COLOR0_TRANSPARENT,
	// 				   16,					// Length of the palette to use (16 colors)
	// 				   (u16*)ttPal,		// Load our 256 color tiles palette
	// 				   (u8*)ttBitmap // image data generated by GRIT
	// 				 );
	

	//important, tex must be pointer or prealocated space w*h * frames count !!!!
	glLoadTileSet( tex,			// pointer to glImage array
					   16,				// sprite width
					   16,				// sprite height
					   128,				// bitmap image width
					   128,				// bitmap image height
					   GL_RGB256,		// texture type for glTexImage2D() in videoGL.h
					   TEXTURE_SIZE_128,	// sizeX for glTexImage2D() in videoGL.h
					   TEXTURE_SIZE_128,	// sizeY for glTexImage2D() in videoGL.h
					   GL_TEXTURE_WRAP_S|GL_TEXTURE_WRAP_T|TEXGEN_OFF|GL_TEXTURE_COLOR0_TRANSPARENT,
					   256,					// Length of the palette to use (16 colors)
					   (u16*)setPal,		// Load our 256 color tiles palette
					   (u8*)setBitmap // image data generated by GRIT
					 );
 
	for(int j=0; j<32; j++){
        initAnim(&sprites[j],STAR_INDEX,STAR_FRAME_COUNT);
        sprites[j].dest_x = (rand()%SCREEN_WIDTH)<<12;
        sprites[j].dest_y = (rand()%SCREEN_HEIGHT)<<12;
        sprites[j].frameCtr = rand()%sprites[j].frames;
        sprites[j].rot  = rand()%2000;
        sprites[j].velrot  = -100 + (rand()%150);
    }
	for(int j=32; j<32+6; j++){
        initAnim(&sprites[j],0, STAR_INDEX-2);
		sprites[j].animating = 0;
		sprites[j].velx = velx;
		sprites[j].frameCtr = rand()%(STAR_INDEX-1);
        sprites[j].dest_x = ((j-32)*64)<<12;
        sprites[j].dest_y = (SCREEN_HEIGHT>>1)<<12;
        sprites[j].rot  = rand()%2000;
        sprites[j].velrot  = -100 + (rand()%10);
    }
}


void onFrame(){
    glBegin2D();

    glBoxFilled(0,0,SCREEN_WIDTH,SCREEN_HEIGHT,RGB15(0,0,2));

	for(int i=0; i<spritesCount; i++){
		
		
		if(i >= 32){
			int xx = sprites[i].dest_x>>12;
			sprites[i].scale =  (1<<12) + (xx*20);
		}
		else{
			sprites[i].scale = (1<<11) - 300;
		}

		drawAnim(&sprites[i]);
		nextFrame(&sprites[i]);
	}

    glEnd2D();
    glFlush(0);
}